/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rainbow_RemoteSomatic_SomaticServiceJNI */

#ifndef _Included_rainbow_RemoteSomatic_SomaticServiceJNI
#define _Included_rainbow_RemoteSomatic_SomaticServiceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rainbow_RemoteSomatic_SomaticServiceJNI
 * Method:    sensorDevOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sva_rainbow_remote_RemoteSomatic_SomaticServiceJNI_sensorDevOpen
  (JNIEnv *, jclass);

/*
 * Class:     rainbow_RemoteSomatic_SomaticServiceJNI
 * Method:    sensorDevIoctl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sva_rainbow_remote_RemoteSomatic_SomaticServiceJNI_sensorDevIoctl
  (JNIEnv *, jclass, jint);

/*
 * Class:     rainbow_RemoteSomatic_SomaticServiceJNI
 * Method:    sensorDevWriteData
 * Signature: (IFFF)I
 */
JNIEXPORT jint JNICALL Java_com_sva_rainbow_remote_RemoteSomatic_SomaticServiceJNI_sensorDevWriteData
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     rainbow_RemoteSomatic_SomaticServiceJNI
 * Method:    sensorDevClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sva_rainbow_remote_RemoteSomatic_SomaticServiceJNI_sensorDevClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
